fix: dralia-7: Set Azure Environment Variables required by terraform to authenticate with Azure (#14)
Error: unable to build authorizer for Resource Manager API: could not configure AzureCli Authorizer: tenant ID was not specified and the default tenant ID could not be determined: obtaining tenant ID: obtaining account details: running Azure CLI